baseurl = "https://math.ucsd.edu/~jbonthiu/harel/"
copyright = "&copy; 2019"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
disqusShortname = ""
enableEmoji = true
enableGitInfo = false
footnotereturnlinkcontents = "<sup>^</sup>"
googleAnalytics = ""
hasCJKLanguage = false
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
paginate = 10
preserveTaxonomyNames = true
theme = "academic"
title = "Guershon Harel"
[blackfriday]
extensions = ["backslashLineBreak"]
fractions = true
hrefTargetBlank = true
smartypants = true
[languages.en]
languageCode = "en-us"
[[menu.main]]
name = "Teaching"
url = "#teaching"
weight = 4
[[menu.main]]
name = "Presentations"
url = "presentation"
weight = 5
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 6
[[menu.main]]
name = "Projects"
url = "#projects"
weight = 3
[[menu.main]]
name = "Publications"
url = "#publications_selected"
weight = 2
[[menu.main]]
name = "Home"
url = "#about"
weight = 1
[outputs]
home = ["HTML", "CSS", "RSS", "JSON"]
section = ["HTML", "RSS"]
[params]
address = "9500 Gilman Drive, Applied Physics and Mathematics BLDG, Room 7420, La Jolla, California 92093-0112 USA"
appointment_url = ""
avatar = "profile.jpg"
color_theme = "default"
comment_count = false
custom_css = []
custom_js = []
date_format = "Jan 2, 2006"
day_night = true
description = ""
email = "harel@math.ucsd.edu"
font = "classic"
gravatar = false
highlight = true
highlight_languages = []
keybase = ""
latitude = "37.4275"
logo = ""
longitude = "-122.1697"
map = 0
map_api_key = ""
math = true
name = "Guershon Harel"
office_hours = ""
phone = "(858) 534-2650"
privacy_pack = false
publication_types = ["Uncategorized", "Conference paper", "Journal article", "Manuscript", "Report", "Book", "Book section"]
reading_time = false
role = "Professor of Mathematics"
section_pager = false
sharing = true
sharing_image = ""
skype = ""
telegram = ""
time_format = "3:04 PM"
twitter = ""
zoom = 15
[params.menus]
align_right = true
[params.projects]
list_children = true
post_format = 2
publication_format = 4
talk_format = 2
[params.publications]
date_format = "January, 2006"
[params.search]
engine = 1
[params.search.algolia]
api_key = ""
app_id = ""
index_name = ""
show_logo = false
[params.talks]
time = true
[[params.organizations]]
name = "UC San Diego"
url = "ucsd.edu"
[[params.social]]
icon = "envelope"
icon_pack = "fas"
link = "#contact"
[taxonomies]
category = "categories"
publication_type = "publication_types"
tag = "tags"
