---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/home
  label: Home
  create: all
  match: "**/*"
- type: directory
  path: content/publication
  label: Publication
  create: documents
  match: "**/*"
  templates:
  - publications
- type: document
  path: content/presentation/_index.md
  label: Presentation
- type: document
  path: content/project/_index.md
  label: Project
upload_dir: static
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: 'pdf/:filename:'
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.53
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.53
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
version: '0.53'
